/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Funcionario;

import CPF.ValidaCPF;
import java.awt.GridLayout;
import java.awt.Insets;
import java.text.ParseException;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Aluno
 */
public class FormFuncionario extends javax.swing.JDialog {

    /**
     * Creates new form FormFuncionario
     */
    public FormFuncionario() {
        initComponents();
        if (func == null) {
            func = new ClasseFuncionario();
        }
        lbVerifica.setVisible(false);
        lbVerifica1.setVisible(false);
        preenche();
    }

    private ClasseFuncionario func;
    private MaskFormatter fmtDoc;
    private String aux = "";
    private boolean salvaEdita = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoBotoes = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbSair = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCpf = new javax.swing.JFormattedTextField();
        cmbFuncao = new javax.swing.JComboBox();
        lbVerifica = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JFormattedTextField();
        lbVerifica1 = new javax.swing.JLabel();
        pnUsuario = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        rbSim = new javax.swing.JRadioButton();
        rbNao = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        btNovo = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btBuscar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblfuncionario = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PubManager V1.0 Cadastro Funcionários");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LogoSistema2.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(240, 204, 153));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel2.setText("Cadastro de Funcionários");

        lbSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit.png"))); // NOI18N
        lbSair.setToolTipText("");
        lbSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSairMouseClicked(evt);
            }
        });

        jLabel8.setText("Sair");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbSair)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbSair)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addGap(29, 29, 29))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Dados do Funcionário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 18))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Nome:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Cpf:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Função:");

        txtNome.setEnabled(false);

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.setText("000.000.000-00");
        txtCpf.setEnabled(false);
        txtCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCpfFocusGained(evt);
            }
        });

        cmbFuncao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ATENDENTE", "ENTREGADOR", "GERENTE" }));
        cmbFuncao.setSelectedIndex(-1);
        cmbFuncao.setEnabled(false);

        lbVerifica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Ok.png"))); // NOI18N
        lbVerifica.setToolTipText("CPF é verdadeiro!");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setText("Telefone:");

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.setText("(000)0000-0000");
        txtTelefone.setEnabled(false);
        txtTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelefoneFocusGained(evt);
            }
        });

        lbVerifica1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cancel.png"))); // NOI18N
        lbVerifica1.setToolTipText("CPF Inexistente!");

        pnUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Dados de Usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 18))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("É Usuário do Sistema?");

        GrupoBotoes.add(rbSim);
        rbSim.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        rbSim.setText("Sim");
        rbSim.setEnabled(false);
        rbSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSimActionPerformed(evt);
            }
        });

        GrupoBotoes.add(rbNao);
        rbNao.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        rbNao.setText("Não");
        rbNao.setEnabled(false);
        rbNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNaoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Senha:");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("Usuário:");

        txtUsuario.setEnabled(false);

        txtSenha.setEnabled(false);

        javax.swing.GroupLayout pnUsuarioLayout = new javax.swing.GroupLayout(pnUsuario);
        pnUsuario.setLayout(pnUsuarioLayout);
        pnUsuarioLayout.setHorizontalGroup(
            pnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnUsuarioLayout.createSequentialGroup()
                        .addComponent(rbSim)
                        .addGap(18, 18, 18)
                        .addComponent(rbNao))
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(txtUsuario)
                    .addComponent(txtSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnUsuarioLayout.setVerticalGroup(
            pnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbSim)
                    .addComponent(rbNao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        btNovo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add.png"))); // NOI18N
        btNovo.setText("<html>Novo<br>Cadastro</html>");
        btNovo.setToolTipText("Cadastra um Novo Funcionário");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btEditar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Edit_text.png"))); // NOI18N
        btEditar.setText("<html>Editar<br>Cadastro</html>");
        btEditar.setEnabled(false);
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btSalvar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Save.png"))); // NOI18N
        btSalvar.setText("<html>Salvar<br>Cadastro</html>");
        btSalvar.setEnabled(false);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btBuscar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Search.png"))); // NOI18N
        btBuscar.setText("<html>Buscar<br>Cadastro</html>");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        btExcluir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Eraser.png"))); // NOI18N
        btExcluir.setText("<html>Excluir<br>Cadastro</html>");
        btExcluir.setEnabled(false);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbVerifica)
                                .addGap(1, 1, 1)
                                .addComponent(lbVerifica1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome))
                        .addGap(28, 28, 28)))
                .addComponent(pnUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lbVerifica1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbVerifica)))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmbFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblfuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblfuncionario.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblfuncionario.getTableHeader().setResizingAllowed(false);
        tblfuncionario.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblfuncionario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void buscaFunc() {
        try {
            if (fmtDoc == null) {
                fmtDoc = new MaskFormatter("###.###.###-##");
            }
        } catch (ParseException ex) {
            System.out.println(ex.getMessage());
        }
        JFormattedTextField dataFormatada = new JFormattedTextField(fmtDoc);
        JLabel rotulo = new JLabel("Digite o CPF do Funcionário:");
        JPanel tela = new JPanel();
        tela.setLayout(new GridLayout(2, 1));
        tela.add(rotulo);
        tela.add(dataFormatada);

        JOptionPane.showMessageDialog(rootPane, tela, "Busca Funcionário", JOptionPane.PLAIN_MESSAGE);
        String cpf = dataFormatada.getText();

        func.setCpf(cpf);
        if (func.buscaFuncionario(func)) {
            preencheCampos();
            btEditar.setEnabled(true);
            btExcluir.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(this, "Não existe nenhum Funcionário\n"
                    + "Cadastrado com este Documento", "Cadastro De Funcionários", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    public void preenche() {
        String aux2 = "SELECT * FROM Funcionarios";

        while (tblfuncionario.getRowCount() > 0) {
            ((DefaultTableModel) tblfuncionario.getModel()).removeRow(0);
        }
        ((DefaultTableModel) tblfuncionario.getModel()).setColumnCount(0);

        tblfuncionario.setModel(func.preencheTabela(aux2));

        tblfuncionario.getTableHeader().setReorderingAllowed(false);

        tblfuncionario.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        for (int i = 0; i <= 4; i++) {
            if (i != 1) {
                tblfuncionario.getColumnModel().getColumn(i).setPreferredWidth(125);
            } else {
                tblfuncionario.getColumnModel().getColumn(i).setPreferredWidth(280);
            }
        }
    }

    public void desbloqueio() {
        txtNome.setEnabled(true);
        txtTelefone.setEnabled(true);
        txtCpf.setEnabled(true);
        cmbFuncao.setEnabled(true);
        rbSim.setEnabled(true);
        rbNao.setEnabled(true);
        btBuscar.setEnabled(false);
        btNovo.setEnabled(false);
        btSalvar.setEnabled(true);
        btEditar.setEnabled(false);
        btExcluir.setEnabled(false);
    }

    public void bloqueio() {
        txtNome.setEnabled(false);
        txtTelefone.setEnabled(false);
        txtCpf.setEnabled(false);
        txtUsuario.setEnabled(false);
        txtSenha.setEnabled(false);
        cmbFuncao.setEnabled(false);
        rbSim.setEnabled(false);
        rbNao.setEnabled(false);
        btSalvar.setEnabled(false);
        btBuscar.setEnabled(true);
        btNovo.setEnabled(true);
        btEditar.setEnabled(false);
        btExcluir.setEnabled(false);
        lbVerifica.setVisible(false);
        lbVerifica1.setVisible(false);
        preenche();
    }

    public void limpaCampos() {
        txtNome.setText(null);
        txtCpf.setText(null);
        txtTelefone.setText(null);
        txtUsuario.setText(null);
        txtSenha.setText(null);
        cmbFuncao.setSelectedIndex(-1);
        GrupoBotoes.clearSelection();
    }

    public void preencheClasse() {
        func.setNome(txtNome.getText().toUpperCase());
        func.setCpf(txtCpf.getText());
        func.setTelefone(txtTelefone.getText());
        func.setFuncao(String.valueOf(cmbFuncao.getSelectedItem()).toUpperCase());
        func.setLogin(txtUsuario.getText().toUpperCase());
        func.setSenha(String.valueOf(txtSenha.getPassword()));
    }

    public void preencheCampos() {
        txtNome.setText(func.getNome());
        txtCpf.setText(func.getCpf());
        txtTelefone.setText(func.getTelefone());
        cmbFuncao.setSelectedItem(func.getFuncao());
        txtUsuario.setText(func.getLogin());
        txtSenha.setText(func.getSenha());
    }

    public boolean verificaCPF() {
        aux = txtCpf.getText().replaceAll("\\.", "");
        aux = aux.replaceAll("-", "");
        if (ValidaCPF.isCPF(aux)) {
            if (func.vfCpfDuplicado("Select * from funcionarios where cpf = '" + txtCpf.getText() + "'")) {
                JOptionPane.showMessageDialog(this, "CPF Ja Cadastrado!", "PubManager.Soft", JOptionPane.INFORMATION_MESSAGE);
                lbVerifica.setVisible(false);
                lbVerifica1.setVisible(true);
                return false;
            } else {
                lbVerifica.setVisible(true);
                lbVerifica1.setVisible(false);
                return true;
            }
        } else {
            JOptionPane.showMessageDialog(this, "Cpf do Funcionário inválido!",
                    "Cadastro de Funcionarios", JOptionPane.WARNING_MESSAGE);
            lbVerifica.setVisible(false);
            lbVerifica1.setVisible(true);
            return false;
        }
    }


    private void lbSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSairMouseClicked
        if (JOptionPane.showConfirmDialog(null, "Deseja fechar esta janela e\nRetornar ao Menu Principal?\n"
                + "Obs: Todos os dados que não\nForem salvos serão perdidos!", "Cadastro de Funcionários", JOptionPane.YES_NO_OPTION)
                == JOptionPane.YES_OPTION) {
            limpaCampos();
            bloqueio();
            this.dispose();
        }
    }//GEN-LAST:event_lbSairMouseClicked

    private void txtCpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCpfFocusGained
        txtCpf.selectAll();
    }//GEN-LAST:event_txtCpfFocusGained

    private void rbSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSimActionPerformed
        txtUsuario.setEnabled(true);
        txtSenha.setEnabled(true);
    }//GEN-LAST:event_rbSimActionPerformed

    private void rbNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNaoActionPerformed
        txtUsuario.setText(null);
        txtSenha.setText(null);
        txtUsuario.setEnabled(false);
        txtSenha.setEnabled(false);
    }//GEN-LAST:event_rbNaoActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        limpaCampos();
        desbloqueio();
    }//GEN-LAST:event_btNovoActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if (!txtNome.getText().equalsIgnoreCase("")) {
            if (verificaCPF()) {
                if (cmbFuncao.getSelectedIndex() != -1) {
                    if (rbSim.isSelected()) {
                        if (!txtUsuario.getText().equalsIgnoreCase("")
                                && !String.valueOf(txtSenha.getPassword()).equalsIgnoreCase("")) {
                            preencheClasse();
                            func.insereFuncionario(func);
                            func.insereUsuario(func);
                            limpaCampos();
                            bloqueio();
                        } else {
                            JOptionPane.showMessageDialog(this, "Favor Preencher os dados de usuário!",
                                    "Cadastro de Funcionarios", JOptionPane.WARNING_MESSAGE);
                        }
                    } else {
                        preencheClasse();
                        func.insereFuncionario(func);
                        limpaCampos();
                        bloqueio();
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Selecione uma Função!",
                            "Cadastro de Funcionarios", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                //Não faz nada, o método se encarrega de exibir a mensagem adequada.
            }
        } else {
            JOptionPane.showMessageDialog(this, "Nome do Funcionário em Branco!",
                    "Cadastro de Funcionarios", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btSalvarActionPerformed

    private void txtTelefoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefoneFocusGained
        txtTelefone.selectAll();
    }//GEN-LAST:event_txtTelefoneFocusGained

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        buscaFunc();
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        if (salvaEdita == false) {
            if (JOptionPane.showConfirmDialog(this, "Deseja Alterar os\nDados do Funcionário?", "Cadastro Funcionários",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                desbloqueio();
                btSalvar.setEnabled(false);
                btEditar.setMargin(new Insets(2, 9, 2, 9));
                btEditar.setText("<html>Salvar<br>Alterações</html>");
                btEditar.setEnabled(true);
                if (!txtUsuario.getText().equals("")) {
                    rbSim.setSelected(true);
                    txtUsuario.setEnabled(true);
                    txtSenha.setEnabled(true);
                }
                salvaEdita = true;
            }
        } else {
            if (JOptionPane.showConfirmDialog(this, "Deseja Salvar os Dados Alterados?", "Cadastro Funcionários",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                if (!txtNome.getText().equalsIgnoreCase("")) {
                    if (verificaCPF()) {
                        if (cmbFuncao.getSelectedIndex() != -1) {
                            if (rbSim.isSelected()) {
                                if (!txtUsuario.getText().equalsIgnoreCase("")
                                        && !String.valueOf(txtSenha.getPassword()).equalsIgnoreCase("")) {
                                    preencheClasse();
                                    func.alteraFuncionario(func);
                                    func.alteraUsuario(func);
                                    limpaCampos();
                                    bloqueio();
                                    btEditar.setMargin(new Insets(2, 14, 2, 14));
                                    btEditar.setText("<html>Editar<br>Produto</html>");
                                    salvaEdita = false;
                                } else {
                                    JOptionPane.showMessageDialog(this, "Favor Preencher os dados de usuário!",
                                            "Cadastro de Funcionarios", JOptionPane.WARNING_MESSAGE);
                                }
                            } else {
                                preencheClasse();
                                func.alteraFuncionario(func);
                                limpaCampos();
                                bloqueio();
                                btEditar.setMargin(new Insets(2, 14, 2, 14));
                                btEditar.setText("<html>Editar<br>Produto</html>");
                                salvaEdita = false;
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "Selecione uma Função!",
                                    "Cadastro de Funcionarios", JOptionPane.WARNING_MESSAGE);
                        }
                    } else {

                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Nome do Funcionário em Branco!",
                            "Cadastro de Funcionarios", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                limpaCampos();
                bloqueio();
                btEditar.setMargin(new Insets(2, 14, 2, 14));
                btEditar.setText("<html>Editar<br>Produto</html>");
                salvaEdita = false;
            }
        }

    }//GEN-LAST:event_btEditarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Deseja excluir o funcionário selecionado?", "Cadastro de Funcionários",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            preencheClasse();
            func.excluiFuncionario(func);
            bloqueio();
            limpaCampos();
            preenche();
        }


    }//GEN-LAST:event_btExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoBotoes;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox cmbFuncao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbSair;
    private javax.swing.JLabel lbVerifica;
    private javax.swing.JLabel lbVerifica1;
    private javax.swing.JPanel pnUsuario;
    private javax.swing.JRadioButton rbNao;
    private javax.swing.JRadioButton rbSim;
    private javax.swing.JTable tblfuncionario;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JFormattedTextField txtTelefone;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
