/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Main;

import Produtos.ClasseProduto;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Aluno
 */
public class TelaMesa extends javax.swing.JDialog {

    /**
     * Creates new form TelaMesa
     */
    public TelaMesa(String numMesa) {
        initComponents();
        lbNumMesa.setText(numMesa);
        tbProdutosMesa.getColumnModel().getColumn(0).setPreferredWidth(5);
        tbProdutosMesa.getColumnModel().getColumn(1).setPreferredWidth(tbProdutosMesa.getColumnModel().getColumn(1).getWidth()+100);
        txtCodProduto.requestFocus();
    }
    
    private pnMesaPadrao objMesa;
    private Object linhas[];
    private DefaultTableModel tabelaAux;
    private ClasseProduto Produto =  new ClasseProduto();
    private final String numeros = "0123456789";
    private final DecimalFormat decimal = new DecimalFormat("0.00");
    private FormFechaVenda frmfechar;
    private FormCupom frmCupom;
    private FormPesquisa frmPesquisa;
    private PesquisaProduto frmPesquisa2;

    
    public DefaultTableModel getTabelaAux() {
        return tabelaAux;
    }
    
    public void setObjMesa(pnMesaPadrao objMesa) {
        this.objMesa = objMesa;
    }
    public pnMesaPadrao getObjMesa() {
        return objMesa;
    }
    
    public void atualizaTotal(){
        double aux = 0;
        for (int i = 0; i < tbProdutosMesa.getRowCount(); i++) {
                aux += Double.valueOf(String.valueOf(tbProdutosMesa.getValueAt(i, 4)).replace(",", "."));
            }
        lbPrecoTotal.setText(decimal.format(aux));
        objMesa.atualizaValor(lbPrecoTotal.getText());
    }
    
    public void insereTabela(){
        if (!txtQuantidade.getText().equals("") && !txtQuantidade.getText().equalsIgnoreCase("0")) {
            int qtd = Produto.buscaQuantidade(Integer.valueOf(txtCodProduto.getText()));
            JOptionPane.showMessageDialog(null,qtd+ "||" +Integer.valueOf(txtQuantidade.getText()) );
            if(!(qtd < Integer.valueOf(txtQuantidade.getText()))){
            if (linhas == null) {
                linhas = new Object[5];
            }
             
            linhas[0] = txtCodProduto.getText();
            linhas[1] = txtDescricao.getText();
            linhas[2] = txtQuantidade.getText();
            linhas[3] = Float.valueOf(txtValor.getText().replaceAll(",", "."));
            linhas[4] = Float.valueOf(txtValor.getText().replaceAll(",", ".")) * Integer.valueOf(txtQuantidade.getText());

            tabelaAux = (DefaultTableModel) tbProdutosMesa.getModel();
            tabelaAux.insertRow(tabelaAux.getRowCount(), linhas);

            atualizaTotal();
            
            limpaFrame();
            }else{
                JOptionPane.showMessageDialog(null,"Quantidade insuficiente no estoque!");
            }
        }else{
           JOptionPane.showMessageDialog(this,"Insira a Quantidade!","PubManager",JOptionPane.INFORMATION_MESSAGE);
        }
            
            
        
        
    }
    
    public void limpaFrame(){
        txtCodProduto.setText("");
        txtDescricao.setText("");
        txtQuantidade.setText("");
        txtValor.setText("");
        
        txtCodProduto.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        lbSair = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbNumMesa = new javax.swing.JLabel();
        Header1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProdutosMesa = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        btInserir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lbPrecoTotal = new javax.swing.JLabel();
        btExcluiItem = new javax.swing.JButton();
        btFechaVenda = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtCodProduto = new javax.swing.JTextField();
        txtQuantidade = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Itens da Mesa/ PubManager.Soft");
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        Header.setBackground(new java.awt.Color(0, 153, 204));
        Header.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lbSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit.png"))); // NOI18N
        lbSair.setToolTipText("");
        lbSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSairMouseClicked(evt);
            }
        });

        jLabel8.setText("Voltar");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setText("Mesa:");

        lbNumMesa.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lbNumMesa.setText("0000");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbNumMesa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(lbSair))
                .addGap(16, 16, 16))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(lbNumMesa))
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addComponent(lbSair)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        Header1.setBackground(new java.awt.Color(0, 153, 204));
        Header1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tbProdutosMesa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DESCRIÇÃO", "QUANTIDADE", "VALOR UNIT.", "VALOR TOTAL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbProdutosMesa.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbProdutosMesa.setShowHorizontalLines(false);
        tbProdutosMesa.setShowVerticalLines(false);
        tbProdutosMesa.getTableHeader().setResizingAllowed(false);
        tbProdutosMesa.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbProdutosMesa);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Itens da Mesa:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Cod. Produto:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Quantidade:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Valor Unitário:");

        txtValor.setEditable(false);

        btInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add.png"))); // NOI18N
        btInserir.setText("INSERIR");
        btInserir.setEnabled(false);
        btInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Descrição:");

        txtDescricao.setEditable(false);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("TOTAL: R$");

        lbPrecoTotal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbPrecoTotal.setText("0,00");

        btExcluiItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Eraser.png"))); // NOI18N
        btExcluiItem.setText("<html><p align=\"Center\">EXCLUIR<br>ITEM</p></html>");
        btExcluiItem.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btExcluiItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluiItemActionPerformed(evt);
            }
        });

        btFechaVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Ok.png"))); // NOI18N
        btFechaVenda.setText("<html><p align=\"Center\">FECHAR<br>VENDA</p></html>");
        btFechaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFechaVendaActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imprimir.png"))); // NOI18N
        jButton3.setText("<html><p align=\"center\">IMPRIME<br>COMANDA</p></html>");
        jButton3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtCodProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodProdutoActionPerformed(evt);
            }
        });
        txtCodProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodProdutoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodProdutoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodProdutoKeyTyped(evt);
            }
        });

        txtQuantidade.setEnabled(false);
        txtQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQuantidadeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQuantidadeKeyTyped(evt);
            }
        });

        jButton1.setText("Selecionar Produto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Header1Layout = new javax.swing.GroupLayout(Header1);
        Header1.setLayout(Header1Layout);
        Header1Layout.setHorizontalGroup(
            Header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Header1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Header1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Header1Layout.createSequentialGroup()
                        .addGroup(Header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5))
                        .addGap(31, 31, 31)
                        .addGroup(Header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Header1Layout.createSequentialGroup()
                                .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btInserir))
                            .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                        .addComponent(btFechaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Header1Layout.createSequentialGroup()
                        .addGroup(Header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Header1Layout.createSequentialGroup()
                                .addGroup(Header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Header1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Header1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(16, 16, 16)))
                                .addGroup(Header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Header1Layout.createSequentialGroup()
                                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(Header1Layout.createSequentialGroup()
                                        .addComponent(txtCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(76, 76, 76)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbPrecoTotal))))
                            .addComponent(jScrollPane1))
                        .addGap(18, 18, 18)
                        .addGroup(Header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btExcluiItem, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        Header1Layout.setVerticalGroup(
            Header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Header1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Header1Layout.createSequentialGroup()
                        .addComponent(btExcluiItem, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(Header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Header1Layout.createSequentialGroup()
                        .addGroup(Header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txtCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(btInserir)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addGroup(Header1Layout.createSequentialGroup()
                        .addGroup(Header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(lbPrecoTotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btFechaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Header1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Header1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSairMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_lbSairMouseClicked

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        objMesa.setaStatus("Ocupada");
    }//GEN-LAST:event_formWindowGainedFocus

    private void btInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirActionPerformed
        insereTabela();
    }//GEN-LAST:event_btInserirActionPerformed

    private void txtCodProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodProdutoKeyReleased
       /* if (!txtCodProduto.getText().equals("")) {
            if (numeros.contains(evt.getKeyChar() + "")) {

                Produto.setIdProduto(Integer.valueOf(txtCodProduto.getText()));

                if (Produto.buscaProduto(Produto)) {
                    txtQuantidade.setEnabled(true);
                    btInserir.setEnabled(true);
                    txtDescricao.setText(Produto.getDescricao());
                    txtValor.setText(String.valueOf(Produto.getPreco()));
                } else {
                    txtDescricao.setText("Produto Não Localizado!");
                    txtValor.setText("");
                    txtQuantidade.setEnabled(false);
                    btInserir.setEnabled(false);
                }
            }
        }else{
            txtDescricao.setText("");
            txtValor.setText("");
            txtQuantidade.setEnabled(false);
            btInserir.setEnabled(false);
        }*/
    }//GEN-LAST:event_txtCodProdutoKeyReleased

    private void txtCodProdutoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodProdutoKeyTyped
        if (!numeros.contains(evt.getKeyChar() + "")) {
            if (evt.getKeyCode() != 0){
                evt.consume();
                txtDescricao.setText("");
                txtValor.setText("");
            }
        }
    }//GEN-LAST:event_txtCodProdutoKeyTyped

    private void txtQuantidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantidadeKeyTyped
        if (!numeros.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtQuantidadeKeyTyped

    private void txtCodProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodProdutoKeyPressed
        if (evt.getKeyCode() == 10){
            txtQuantidade.requestFocus();
        }
    }//GEN-LAST:event_txtCodProdutoKeyPressed

    private void txtQuantidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantidadeKeyPressed
        if (evt.getKeyCode() == 10){
            insereTabela();
        }
    }//GEN-LAST:event_txtQuantidadeKeyPressed

    private void btFechaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFechaVendaActionPerformed
        if(tabelaAux == null){
            JOptionPane.showMessageDialog(this, "Nenhum Item Vendido!",
                    "PubManager.Soft",JOptionPane.INFORMATION_MESSAGE);
        }
        else if (JOptionPane.showConfirmDialog(this, "Deseja Finalizar a Venda?",
                "PubManager.Soft", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            if (frmfechar == null) {
                frmfechar = new FormFechaVenda();
            }
            frmfechar.setTelaPai(this);
            this.setVisible(false);
            frmfechar.setModal(true);
            frmfechar.valores(lbNumMesa.getText(), lbPrecoTotal.getText(), tabelaAux);
            frmfechar.setVisible(true);
        }
    }//GEN-LAST:event_btFechaVendaActionPerformed

    private void btExcluiItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluiItemActionPerformed
        if (tbProdutosMesa.getSelectedRow() > -1){
            if (JOptionPane.showConfirmDialog(this, "Deseja Excluir o Produto Selecionado?", "PubManager.Soft",
                        JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                tabelaAux.removeRow(tbProdutosMesa.getSelectedRow());
                atualizaTotal();
            }
        }
    }//GEN-LAST:event_btExcluiItemActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (tabelaAux != null){
            if (frmCupom == null){
                frmCupom = new FormCupom();
            }

            frmCupom.setModal(true);
            frmCupom.setItensMesa(tabelaAux);
            frmCupom.setNumMesa(lbNumMesa.getText());
            frmCupom.setTotalMesa(lbPrecoTotal.getText().replaceAll(",","."));
            frmCupom.preencheLista();

            frmCupom.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Nenhum Item Vendido!",
                    "Siscodi",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        objMesa.atualizaValor(lbPrecoTotal.getText());
    }//GEN-LAST:event_formWindowClosed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        txtCodProduto.setText("");
        txtDescricao.setText("");
        txtValor.setText("");
        PesquisaProduto2 PP = new PesquisaProduto2(null,true);
        PP.setAlwaysOnTop(true);
        PP.setVisible(true);
        int id;
        id = Produto.buscaIdAuxiliar();
        Produto.setIdProduto(id);
         if (Produto.buscaProduto(Produto)) {                 
                    txtQuantidade.setEnabled(true);
                    btInserir.setEnabled(true);
                    txtCodProduto.setText(String.valueOf(Produto.getIdProduto()));
                    txtDescricao.setText(Produto.getDescricao());
                    txtValor.setText(String.valueOf(Produto.getPreco()));
                } else {
                    txtDescricao.setText("Produto Não Localizado!");
                    txtValor.setText("");
                    txtQuantidade.setEnabled(false);
                    btInserir.setEnabled(false);
                }
         Produto.apagarIdAuxiliar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCodProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TelaMesa().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Header1;
    private javax.swing.JButton btExcluiItem;
    private javax.swing.JButton btFechaVenda;
    private javax.swing.JButton btInserir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbNumMesa;
    private javax.swing.JLabel lbPrecoTotal;
    private javax.swing.JLabel lbSair;
    private javax.swing.JTable tbProdutosMesa;
    private javax.swing.JTextField txtCodProduto;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
